// src/constants/programSchema.js

export const PROGRAM_SCHEMA = {
  title: "",
  slug: "",
  category: "",
  status: "active",
  thumbnail: "",
  banner: "",
  heroImage: "",
  overviewImage: "",
  tagline: "",
  shortDescription: "",
  fullDescription: "",
  instructor: "",
  duration: "",
  schedule: "",
  location: "",
  sections: [],
  features: [],
  objectives: [],
  gallery: [],
  stats: {
    totalStudents: 0,
    totalStaff: 0,
    yearsRunning: 0,
  },
  categories: [],
  staffHighlights: [],
  testimonials: [],
  verse: null,
  islamicIntegration: [],
  startDate: "",
  endDate: "",
  isFeatured: false,
  createdAt: "",
  updatedAt: "",
}
